# -*- coding: utf-8 -*-
"""Pro-109

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o9hxQKofMkAYIZNt8HNDg4h1LCsB1vZk
"""

import plotly.figure_factory as ff
import plotly.graph_objects as go
import statistics
import pandas as pd
import random
import csv

df=pd.read_csv("StudentsPerformance.csv")
math= df["reading score"].tolist()

mean = sum(math) / len(math)
std_deviation = statistics.stdev(math)
median = statistics.median(math)
mode = statistics.mode(math)

first_std_deviation_start, first_std_deviation_end = mean-std_deviation, mean+std_deviation
second_std_deviation_start, second_std_deviation_end = mean-(2*std_deviation), mean+(2*std_deviation)
third_std_deviation_start, third_std_deviation_end = mean-(3*std_deviation), mean+(3*std_deviation)

fig = ff.create_distplot([math], ["Result"], show_hist=False)
fig.add_trace(go.Scatter(x=[mean, mean], y=[0, 0.17], mode="lines", name="Mean"))
fig.add_trace(go.Scatter(x=[first_std_deviation_start, first_std_deviation_start], y=[0, 0.17], mode="lines", name="Quarter 2"))
fig.add_trace(go.Scatter(x=[first_std_deviation_end, first_std_deviation_end], y=[0, 0.17], mode="lines", name="Quarter 3"))
fig.add_trace(go.Scatter(x=[second_std_deviation_start, second_std_deviation_start], y=[0, 0.17], mode="lines", name="Quarter 1"))
fig.add_trace(go.Scatter(x=[second_std_deviation_end, second_std_deviation_end], y=[0, 0.17], mode="lines", name="Quarter 4"))
fig.show()